FROM node:20

WORKDIR /usr/src/app

COPY ./src/udp-server.js ./
COPY ./src/package*.json ./
COPY ./src/*-util.js ./
COPY ./src/counter-service/ ./counter-service/

ENV PORT=5557
EXPOSE 5557
CMD [ "node", "udp-server.js" ]