apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-server-clustering
  labels:
    app: tally
spec:
  selector:
    matchLabels:
      app: tally
  template:
    metadata:
      labels:
        app: tally
    spec:
      containers:
      - name: tcp-server-clustering
        image: tcp-clustering
        ports:
        - containerPort: 5556